### ISSUE TITLE
onCropImage return bytes with black image on web

### ISSUE THREAD

**Issue by VagnerWillian** [icapps/flutter-custom-image-crop#22] opened 2022-10-25 10:07 UTC
On Mobile it works perfectly, however, on the web, the onCropImage function returns bytes with a black image, invalid bytes.
Help-me!

**Comment by ikbendewilliam** [comment] 2022-10-25 11:30
Hi, we are aware of this. There is an issue with drawing on canvas. For more information, see #9 

>I've fixed the drawing, you can check it out [here](https://github.com/icapps/flutter-custom-image-crop/tree/bugfix/image-on-html-not-drawn-correct). The cropping itself is not working yet.

I'm working on a solution, but it's not really priority for us, therefore I can't give you an ETA. 
Feel free to have a look yourself 😉

**Comment by ikbendewilliam** [comment] 2022-10-25 11:30
Duplicate of #9

**Closed by ikbendewilliam** 2022-10-25 11:30 UTC
